export const rawProducts = [
  {
    slug: "bugis-folding-chair",
    name: "Bugis Folding Chair",
    sku: "ONE59-DIN-001",
    categorySlug: "dining",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 39,
    image: "/images/folding-chair.webp",
    tone: "ember",
    badge: "Drop pick",
    stockStatus: "in_stock",
    summary: "A slim steel folding chair that disappears fast when guests leave.",
    highlights: [
      "Pre-assembled and ready to use out of the box",
      "Easy fold profile for tighter dining corners",
      "Textured seat that wipes down quickly after everyday meals",
    ],
    dimensions: "W45 × D46 × H78 cm",
    materials: "Powder-coated steel frame, textured PP seat",
    finish: "Matte sand seat with black frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Dining corners, hot-desk guests, rental kitchens" },
      { label: "Care", value: "Wipe clean with a soft damp cloth" },
      { label: "Weight", value: "3.6 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 64,
      quote: "Bought two for weekday dinners and they still look good enough for weekend guests.",
      person: "Nadia, Queenstown",
    },
    alternativeSlugs: ["marina-tray-table"],
  },
  {
    slug: "marina-tray-table",
    name: "Marina Tray Table",
    sku: "ONE59-DIN-002",
    categorySlug: "dining",
    catalogType: "evergreen",
    price: 79,
    image: "/images/tray-table.webp",
    tone: "sand",
    badge: "Evergreen",
    stockStatus: "in_stock",
    summary: "A fold-flat tray table for late breakfasts, laptop lunches, and flexible hosting.",
    highlights: [
      "Tucks away when the floor plan needs to change",
      "Rounded edges keep the look softer in tighter rooms",
      "Factory-direct pricing keeps it well under the S$159 promise",
    ],
    dimensions: "W58 × D38 × H66 cm",
    materials: "Bamboo top, powder-coated steel base",
    finish: "Warm natural bamboo",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Breakfast setups, laptops, side serving" },
      { label: "Care", value: "Dry cloth or mild soap only" },
      { label: "Weight", value: "4.8 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 87,
      quote: "Looks far more expensive than S$79 and arrived exactly when promised.",
      person: "Marcus, Bukit Panjang",
    },
    alternativeSlugs: ["bugis-folding-chair"],
  },
  {
    slug: "tanjong-floor-cushion",
    name: "Tanjong Floor Cushion",
    sku: "ONE59-LIV-001",
    categorySlug: "living",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 49,
    image: "/images/floor-cushion.webp",
    tone: "clay",
    badge: "Live drop",
    stockStatus: "low_stock",
    summary: "An oversized floor cushion for movie nights, reading corners, and low-lift hosting.",
    highlights: [
      "Soft enough for lounging, structured enough to hold shape",
      "Works in living rooms, study corners, and nursery spillover zones",
      "Comes pre-filled so there is no setup drama on arrival",
    ],
    dimensions: "W68 × D68 × H18 cm",
    materials: "Cotton blend cover, polyfill insert",
    finish: "Clay beige",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Movie nights, reading corners, extra guests" },
      { label: "Care", value: "Spot clean outer cover only" },
      { label: "Weight", value: "2.4 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 38,
      quote: "We bought one as a trial and went back for a second by the weekend.",
      person: "Elaine, Tampines",
    },
    alternativeSlugs: ["toa-plastic-stool"],
  },
  {
    slug: "toa-plastic-stool",
    name: "Toa Utility Stool",
    sku: "ONE59-LIV-002",
    categorySlug: "living",
    catalogType: "evergreen",
    price: 29,
    image: "/images/plastic-stool.webp",
    tone: "sage",
    badge: "Fast mover",
    stockStatus: "sold_out",
    summary: "A stack-friendly stool that works as a seat, side perch, or plant stand in a pinch.",
    highlights: [
      "Useful in balconies, bathrooms, and hosting overflow",
      "Lightweight build makes room resets easy",
      "Popular as a quick win for smaller flats",
    ],
    dimensions: "W31 × D31 × H45 cm",
    materials: "High-density molded plastic",
    finish: "Soft olive matte",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore when restocked",
    specs: [
      { label: "Best for", value: "Balconies, side seating, plant styling" },
      { label: "Care", value: "Wipe clean and avoid harsh abrasives" },
      { label: "Weight", value: "1.9 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 112,
      quote: "Sold out before I could buy a second one, which says everything.",
      person: "Aqilah, Jurong East",
    },
    alternativeSlugs: ["tanjong-floor-cushion"],
  },
  {
    slug: "joo-chiat-bedside-table",
    name: "Joo Chiat Bedside Table",
    sku: "ONE59-BED-001",
    categorySlug: "bedroom",
    catalogType: "evergreen",
    price: 129,
    image: "/images/bedside-table.webp",
    tone: "sand",
    badge: "Best seller",
    stockStatus: "low_stock",
    summary: "A clean-lined bedside table with one drawer and just enough storage for the nightly essentials.",
    highlights: [
      "Drawer hides the visual clutter quickly",
      "Compact footprint suits HDB and condo bedrooms alike",
      "Arrives fully built so setup takes minutes, not hours",
    ],
    dimensions: "W42 × D35 × H50 cm",
    materials: "Engineered wood, melamine finish, powder-coated handle",
    finish: "Warm oat woodgrain",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Bedside storage, guest rooms, rental upgrades" },
      { label: "Care", value: "Dry cloth and no standing water" },
      { label: "Weight", value: "11.2 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 71,
      quote: "The finish feels calm and expensive without pushing over budget.",
      person: "Jia Xin, Hougang",
    },
    alternativeSlugs: ["sengkang-wall-mirror"],
  },
  {
    slug: "sengkang-wall-mirror",
    name: "Sengkang Wall Mirror",
    sku: "ONE59-BED-002",
    categorySlug: "bedroom",
    catalogType: "evergreen",
    price: 59,
    image: "/images/wall-mirror.webp",
    tone: "slate",
    badge: "Always on",
    stockStatus: "in_stock",
    summary: "A minimal wall mirror that brightens smaller rooms and entry-side corners instantly.",
    highlights: [
      "Soft rounded frame keeps the look lighter than a square mirror",
      "Works equally well in bedrooms, dressing corners, and entry walls",
      "A high-impact refresh for under S$59 with GST already included",
    ],
    dimensions: "W46 × D3 × H66 cm",
    materials: "Aluminium frame, mirrored glass",
    finish: "Graphite frame",
    assembly: "Wall mount required",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Visual light, outfit checks, entry styling" },
      { label: "Care", value: "Glass cleaner on cloth, not directly on mirror" },
      { label: "Weight", value: "4.4 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 58,
      quote: "The proportions are just right for compact bedrooms in Singapore apartments.",
      person: "Darren, Serangoon",
    },
    alternativeSlugs: ["joo-chiat-bedside-table"],
  },
  {
    slug: "queenstown-desk-lamp",
    name: "Queenstown Desk Lamp",
    sku: "ONE59-WRK-001",
    categorySlug: "workspace",
    catalogType: "drop",
    dropSlug: "study-corner",
    price: 45,
    image: "/images/desk-lamp.webp",
    tone: "ember",
    badge: "Night shift",
    stockStatus: "in_stock",
    summary: "A compact desk lamp with a clean silhouette and warm task lighting for WFH corners.",
    highlights: [
      "Helps smaller desks feel styled, not temporary",
      "Warm light tone flatters study corners during late hours",
      "Pairs naturally with slim desks and storage bins",
    ],
    dimensions: "W18 × D18 × H39 cm",
    materials: "Powder-coated steel, ABS diffuser",
    finish: "Burnt sienna",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Study corners, bedroom desks, night reading" },
      { label: "Care", value: "Soft dry cloth only" },
      { label: "Weight", value: "1.4 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 42,
      quote: "Exactly the kind of desk lamp you see in moodboards, minus the scary price.",
      person: "Faris, Clementi",
    },
    alternativeSlugs: ["paya-laptop-desk"],
  },
  {
    slug: "paya-laptop-desk",
    name: "Paya Laptop Desk",
    sku: "ONE59-WRK-002",
    categorySlug: "workspace",
    catalogType: "evergreen",
    price: 99,
    image: "/images/laptop-desk.webp",
    tone: "slate",
    badge: "WFH staple",
    stockStatus: "in_stock",
    summary: "A narrow-profile laptop desk for getting a proper setup into rooms that do not really have room.",
    highlights: [
      "Slim depth keeps circulation clear in shared rooms",
      "Built for laptops, notebooks, and compact monitors",
      "A good match for the current study-corner drop window",
    ],
    dimensions: "W80 × D40 × H75 cm",
    materials: "Powder-coated steel, laminate top",
    finish: "Charcoal frame with ash top",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "WFH setups, tuition desks, compact bedrooms" },
      { label: "Care", value: "Soft cloth and mild cleaner" },
      { label: "Weight", value: "8.3 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 93,
      quote: "The exact reason I tried One59 — it looks designed, not makeshift.",
      person: "Melissa, Bedok",
    },
    alternativeSlugs: ["queenstown-desk-lamp"],
  },
  {
    slug: "hougang-cube-bin",
    name: "Hougang Cube Bin",
    sku: "ONE59-STO-001",
    categorySlug: "storage",
    catalogType: "evergreen",
    price: 19,
    image: "/images/cube-bin.webp",
    tone: "sage",
    badge: "Fast restock",
    stockStatus: "in_stock",
    summary: "A soft-sided storage cube that makes open shelving look deliberate instead of messy.",
    highlights: [
      "Folds flat when not in use",
      "Tidy enough for open shelves in living rooms and bedrooms",
      "One of the lowest-friction under-S$159 entry points to the brand",
    ],
    dimensions: "W29 × D29 × H29 cm",
    materials: "Fabric shell, reinforced insert base",
    finish: "Warm stone",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Open shelves, toys, cables, wardrobe extras" },
      { label: "Care", value: "Spot clean and air dry" },
      { label: "Weight", value: "0.7 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 121,
      quote: "The quickest way to make a shelf look finished before people come over.",
      person: "Hui Min, Pasir Ris",
    },
    alternativeSlugs: ["yishun-wall-shelf", "bedok-shoe-rack"],
  },
  {
    slug: "yishun-wall-shelf",
    name: "Yishun Wall Shelf",
    sku: "ONE59-STO-002",
    categorySlug: "storage",
    catalogType: "drop",
    dropSlug: "payday-reset",
    price: 55,
    image: "/images/wall-shelf.webp",
    tone: "sage",
    badge: "Drop exclusive",
    stockStatus: "sold_out",
    summary: "A shallow wall shelf for decor, daily grab items, and visual storage above the floor line.",
    highlights: [
      "Perfect for vertical storage when floor space is tight",
      "Styled enough for bedrooms, entryways, and WFH corners",
      "The first item to sell through in the current payday drop",
    ],
    dimensions: "W60 × D18 × H20 cm",
    materials: "Pine veneer shelf, concealed bracket",
    finish: "Mid-oak",
    assembly: "Wall mount required",
    delivery: "Ships in 3 to 5 days across mainland Singapore on next allocation",
    specs: [
      { label: "Best for", value: "Vertical storage, display, entry essentials" },
      { label: "Care", value: "Dust with a dry microfiber cloth" },
      { label: "Weight", value: "3.8 kg" },
    ],
    socialProof: {
      rating: 4.8,
      reviews: 55,
      quote: "Exactly the kind of product that sells out because every room can use one.",
      person: "Rina, Sembawang",
    },
    alternativeSlugs: ["hougang-cube-bin", "bedok-shoe-rack", "ang-mo-kio-coat-rack"],
  },
  {
    slug: "bedok-shoe-rack",
    name: "Bedok Shoe Rack",
    sku: "ONE59-STO-003",
    categorySlug: "storage",
    catalogType: "evergreen",
    price: 89,
    image: "/images/shoe-rack.webp",
    tone: "sand",
    badge: "Entryway fix",
    stockStatus: "in_stock",
    summary: "A compact shoe rack with enough polish to stay visible instead of being hidden away.",
    highlights: [
      "Keeps everyday pairs organised without looking utilitarian",
      "Works especially well with mirrors and coat stands in smaller foyers",
      "Designed to make the first 2 metres of your home feel calmer",
    ],
    dimensions: "W72 × D28 × H54 cm",
    materials: "Powder-coated steel, wood-look shelves",
    finish: "Sand oak shelves with charcoal frame",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore",
    specs: [
      { label: "Best for", value: "Entryways, rental foyers, spare-room doors" },
      { label: "Care", value: "Dry cloth or mild soap" },
      { label: "Weight", value: "6.1 kg" },
    ],
    socialProof: {
      rating: 4.9,
      reviews: 79,
      quote: "Made our entrance look intentional instead of like a shoe pile.",
      person: "Shafiq, Woodlands",
    },
    alternativeSlugs: ["ang-mo-kio-coat-rack", "hougang-cube-bin"],
  },
  {
    slug: "ang-mo-kio-coat-rack",
    name: "Ang Mo Kio Coat Rack",
    sku: "ONE59-STO-004",
    categorySlug: "storage",
    catalogType: "drop",
    dropSlug: "entryway-flip",
    price: 119,
    image: "/images/coat-rack.webp",
    tone: "clay",
    badge: "Upcoming drop",
    stockStatus: "in_stock",
    summary: "A vertical coat rack that makes the entryway feel sorted before anyone reaches the living room.",
    highlights: [
      "Tall profile, small footprint",
      "Eight hooks handle bags, umbrellas, and quick-grab layers",
      "Set up for the next drop window with the entryway collection",
    ],
    dimensions: "W38 × D38 × H170 cm",
    materials: "Solid rubberwood, matte protective coat",
    finish: "Smoked walnut",
    assembly: "Pre-assembled",
    delivery: "Ships in 3 to 5 days across mainland Singapore once the drop opens",
    specs: [
      { label: "Best for", value: "Entryways, bedrooms, guest-ready resets" },
      { label: "Care", value: "Dry cloth and occasional wood-safe polish" },
      { label: "Weight", value: "7.5 kg" },
    ],
    socialProof: {
      rating: 4.7,
      reviews: 24,
      quote: "The upcoming drop piece everyone in our group chat saved first.",
      person: "Wei Lin, Bishan",
    },
    alternativeSlugs: ["bedok-shoe-rack", "hougang-cube-bin"],
  },
];
